#!/bin/sh
# set -eu

realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo  "$REALPATH"
}
#realpath "$@"

PROJECT_ROOT=$(realpath)   # or result=`myfunc`
ANKI_REPO_URL=${ANKI_REPO_URL:-"https://github.com/ankitects/anki"}
ANKI_COMMIT=7437ce41ec66a81b0e78096649a503b364a4025a

#PROJECT_ROOT="$(realpath "$(dirname "$(dirname "$0")")")"
ANKI_PATCH_FOLDER="$PROJECT_ROOT./anki_patch/"
ANKI_FILE_SUFFIX="_anki_rslib.patch"

echo "Cloning anki from $ANKI_REPO_URL"
cd "$PROJECT_ROOT"
# remove anki lib in case patched cache exists in docker build during github action
rm -fr anki
git clone "$ANKI_REPO_URL"
echo "Checking out commit $ANKI_COMMIT and applying patch"
cd anki
git checkout $ANKI_COMMIT
git apply "$ANKI_PATCH_FOLDER/$ANKI_COMMIT$ANKI_FILE_SUFFIX"
